FROM microbusiness/protobuf-builder:latest
LABEL maintainer="morteza.alizadeh@gmail.com"

ADD ./contract/grpc /src
WORKDIR /src/proto
RUN mkdir -p ../go
RUN protoc \
    --go_opt=Mproject-commons.proto=./ \
    --go_opt=Mproject-messages.proto=./ \
    --go_opt=Mproject-operations.proto=./ \
    *.proto \
    --go_out=plugins=grpc:../go
