FROM decentralizedcloud/golang-test-and-coverage-base:252
LABEL maintainer="morteza.alizadeh@gmail.com"

ARG CI_SERVICE
ARG COVERALLS_TOKEN

ADD . /src
WORKDIR /src

RUN go test -v -covermode=count -coverprofile=coverage.out ./...
RUN goveralls -coverprofile=coverage.out -service=$CI_SERVICE -repotoken $COVERALLS_TOKEN

