version: "3.7"
services:
  mongodb:
    image: mongo:4.2.1
    ports:
      - 27017
    networks:
      - the_net

  tenant:
    build:
      context: ../
      dockerfile: docker/Dockerfile.integrationTest
    depends_on:
      - mongodb
    networks:
      - the_net

networks:
  the_net:
