FROM microbusiness/protobuf-builder:latest
LABEL maintainer="morteza.alizadeh@gmail.com"

ADD . /src
WORKDIR /src/contract/grpc/proto
RUN protoc --go_opt=Mproject.proto=/src/contract/grpc/proto project.proto --go_out=plugins=grpc:../go
