// Code generated by MockGen. DO NOT EDIT.
// Source: ../contract/configuration-service-contract.go

// Package mock_contract is a generated GoMock package.
package mock_contract

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockConfigurationServiceContract is a mock of ConfigurationServiceContract interface
type MockConfigurationServiceContract struct {
	ctrl     *gomock.Controller
	recorder *MockConfigurationServiceContractMockRecorder
}

// MockConfigurationServiceContractMockRecorder is the mock recorder for MockConfigurationServiceContract
type MockConfigurationServiceContractMockRecorder struct {
	mock *MockConfigurationServiceContract
}

// NewMockConfigurationServiceContract creates a new mock instance
func NewMockConfigurationServiceContract(ctrl *gomock.Controller) *MockConfigurationServiceContract {
	mock := &MockConfigurationServiceContract{ctrl: ctrl}
	mock.recorder = &MockConfigurationServiceContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockConfigurationServiceContract) EXPECT() *MockConfigurationServiceContractMockRecorder {
	return m.recorder
}

// GetPort mocks base method
func (m *MockConfigurationServiceContract) GetPort() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPort")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPort indicates an expected call of GetPort
func (mr *MockConfigurationServiceContractMockRecorder) GetPort() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPort", reflect.TypeOf((*MockConfigurationServiceContract)(nil).GetPort))
}

// GetHost mocks base method
func (m *MockConfigurationServiceContract) GetHost() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHost")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHost indicates an expected call of GetHost
func (mr *MockConfigurationServiceContractMockRecorder) GetHost() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHost", reflect.TypeOf((*MockConfigurationServiceContract)(nil).GetHost))
}
