// Code generated by MockGen. DO NOT EDIT.
// Source: ../contract/configuration-service-contract.go

// Package mock_contract is a generated GoMock package.
package mock_contract

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockConfigurationServiceContract is a mock of ConfigurationServiceContract interface
type MockConfigurationServiceContract struct {
	ctrl     *gomock.Controller
	recorder *MockConfigurationServiceContractMockRecorder
}

// MockConfigurationServiceContractMockRecorder is the mock recorder for MockConfigurationServiceContract
type MockConfigurationServiceContractMockRecorder struct {
	mock *MockConfigurationServiceContract
}

// NewMockConfigurationServiceContract creates a new mock instance
func NewMockConfigurationServiceContract(ctrl *gomock.Controller) *MockConfigurationServiceContract {
	mock := &MockConfigurationServiceContract{ctrl: ctrl}
	mock.recorder = &MockConfigurationServiceContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockConfigurationServiceContract) EXPECT() *MockConfigurationServiceContractMockRecorder {
	return m.recorder
}

// GetGRPCPort mocks base method
func (m *MockConfigurationServiceContract) GetGRPCPort() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGRPCPort")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGRPCPort indicates an expected call of GetGRPCPort
func (mr *MockConfigurationServiceContractMockRecorder) GetGRPCPort() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGRPCPort", reflect.TypeOf((*MockConfigurationServiceContract)(nil).GetGRPCPort))
}

// GetGRPCHost mocks base method
func (m *MockConfigurationServiceContract) GetGRPCHost() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGRPCHost")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGRPCHost indicates an expected call of GetGRPCHost
func (mr *MockConfigurationServiceContractMockRecorder) GetGRPCHost() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGRPCHost", reflect.TypeOf((*MockConfigurationServiceContract)(nil).GetGRPCHost))
}
